-- FD

SELECT NO_OF_EMP
FROM DEPARTMENT
GROUP BY NO_OF_EMP
HAVING COUNT (DISTINCT DEPT_ID) > 1;

SELECT DEPT_NAME
FROM DEPARTMENT
GROUP BY DEPT_NAME
HAVING COUNT (DISTINCT NO_OF_EMP) > 1;

-- NESTED QUERY

SELECT A.DEPT_NAME
FROM DEPARTMENT A
WHERE A.DEPT_ID IN  (	SELECT B.DEPT_ID
						FROM EMPLOYEE B
						WHERE B.SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEE)
					);

SELECT DISTINCT A.OPERATOR
FROM CALL A
WHERE A.CUST_ID IN (
					SELECT B.CUST_ID
					FROM CUSTOMER B
					WHERE B.EMAIL_ID LIKE 'R%'
					);

-- LEFT OUTER JOIN

SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, CUSTOMER.CUST_ID, CUSTOMER.NAME, EMPLOYEE.CITY
FROM CUSTOMER
LEFT JOIN EMPLOYEE ON EMPLOYEE.CITY=CUSTOMER.CITY
ORDER BY CUSTOMER.CUST_ID;

-- AGGREGATE QUERY

SELECT min([DURATION(m)]) AS Min_duration
FROM CALL_LOG;

SELECT max([DURATION(m)]) AS Max_duration
FROM CALL_LOG;

SELECT avg([DURATION(m)]) AS Avg_duration
FROM CALL_LOG;

SELECT count(DEPT_ID) AS [No of departments]
FROM DEPARTMENT;

-- NATURAL_JOIN

SELECT *
FROM CALL_LOG A
INNER JOIN CALL B ON B.CALL_ID = A.CALL_ID;